openapi: 3.1.0
info:
  title: MMDB Server API
  description: |
    An open source fast API server to lookup IP addresses for their geographic location.
    The server provides detailed geolocation information including country data, ASN information, and more.

    ## Error Handling
    The API uses standard HTTP status codes:
    - 200: Successful response
    - 422: Invalid input (e.g., malformed IP address)
    - 500: Server error

    ## Response Format
    All successful responses return an array of results, as the server may query multiple MMDB databases.
  version: '0.5'
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  contact:
    name: Daniel
    url: https://github.com/hireflix/mmdb-server
    email: daniel@hireflix.com

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.example.com/v1
    description: Production server (example)

tags:
  - name: Geolocation
    description: IP geolocation endpoints
  - name: Utility
    description: Utility endpoints

paths:
  /geolookup/{ip}:
    get:
      tags:
        - Geolocation
      summary: Look up geolocation information for an IP address
      description: |
        Returns detailed geolocation data for the specified IPv4 or IPv6 address.
        The response includes country information, ASN details, and metadata about the MMDB databases used.
      parameters:
        - name: ip
          in: path
          required: true
          description: IPv4 or IPv6 address to look up
          schema:
            type: string
            format: ipv4|ipv6
          examples:
            ipv4:
              value: "8.8.8.8"
              summary: Google DNS IPv4
            ipv6:
              value: "2001:4860:4860::8888"
              summary: Google DNS IPv6
      responses:
        '200':
          description: Successful geolocation lookup
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeoResponse'
              examples:
                google_dns:
                  summary: Google DNS lookup
                  value:
                    - country:
                        iso_code: "US"
                        AutonomousSystemNumber: "15169"
                        AutonomousSystemOrganization: "GOOGLE"
                      meta:
                        description:
                          en: "Geo Open MMDB database - https://github.com/hireflix/mmdb-server"
                        build_db: "2024-03-20 07:34:35"
                        db_source: "GeoOpen-Country-ASN"
                        nb_nodes: 1347239
                      ip: "8.8.8.8"
                      country_info:
                        Country: "United States"
                        Alpha-2 code: "US"
                        Alpha-3 code: "USA"
                        Numeric code: "840"
                        Latitude (average): "38"
                        Longitude (average): "-97"
                cloudflare:
                  summary: Cloudflare DNS lookup
                  value:
                    - country:
                        iso_code: "US"
                        AutonomousSystemNumber: "13335"
                        AutonomousSystemOrganization: "CLOUDFLARE"
                      meta:
                        description:
                          en: "Geo Open MMDB database - https://github.com/hireflix/mmdb-server"
                        build_db: "2024-03-20 07:34:35"
                        db_source: "GeoOpen-Country-ASN"
                        nb_nodes: 1347239
                      ip: "1.1.1.1"
                      country_info:
                        Country: "United States"
                        Alpha-2 code: "US"
                        Alpha-3 code: "USA"
                        Numeric code: "840"
                        Latitude (average): "38"
                        Longitude (average): "-97"
        '422':
          description: Invalid IP address format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: string
                  details:
                    type: string
              example:
                error: "Invalid IP address format"
                code: "INVALID_IP"
                details: "IPv4 or IPv6 address is in an incorrect format. Dotted decimal for IPv4 or textual representation for IPv6 are required."

  /:
    get:
      tags:
        - Utility
      summary: Get geolocation information for the requesting client
      description: |
        Returns geolocation data for the client's IP address.
        This is useful for determining the geographic location of the current user.
      responses:
        '200':
          description: Successful geolocation lookup
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GeoResponse'

components:
  schemas:
    GeoResponse:
      type: object
      required:
        - country
        - meta
        - ip
      properties:
        country:
          type: object
          required:
            - iso_code
          properties:
            iso_code:
              type: string
              description: Two-letter ISO country code
              example: "US"
            AutonomousSystemNumber:
              type: string
              description: ASN number (only in ASN database responses)
              example: "15169"
            AutonomousSystemOrganization:
              type: string
              description: Organization operating the AS (only in ASN database responses)
              example: "GOOGLE"
        meta:
          type: object
          required:
            - description
            - build_db
            - db_source
            - nb_nodes
          properties:
            description:
              type: object
              properties:
                en:
                  type: string
                  example: "Geo Open MMDB database - https://github.com/hireflix/mmdb-server"
            build_db:
              type: string
              format: date-time
              example: "2024-03-20 07:34:35"
            db_source:
              type: string
              example: "GeoOpen-Country-ASN"
            nb_nodes:
              type: integer
              example: 1347239
        ip:
          type: string
          format: ipv4
          example: "8.8.8.8"
        country_info:
          type: object
          properties:
            Country:
              type: string
              example: "United States"
            Alpha-2 code:
              type: string
              example: "US"
            Alpha-3 code:
              type: string
              example: "USA"
            Numeric code:
              type: string
              example: "840"
            Latitude (average):
              type: string
              example: "38"
            Longitude (average):
              type: string
              example: "-97"